dist: xenial
language: python
python: 3.6.7
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest --cov=imgresizer
after_success:
  - COVERALLS_REPO_TOKEN=A5hzTMHk3NzWo9yzUPRpwWvH3oKHKhmzq coveralls

